// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicClubs22 } from "./plasmic/proliga/PlasmicClubs22";

function Clubs22_(props, ref) {
  // Use PlasmicClubs22 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicClubs22 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Clubs22Props here, but feel free
  // to do whatever works for you.
  return <PlasmicClubs22 root={{ ref }} {...props} />;
}

const Clubs22 = React.forwardRef(Clubs22_);

export default Clubs22;
