// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDWy3GXn2mzd9e2xUaPdmu
// Component: Bqv9LwfAil9f
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import Navbar from "../../Navbar"; // plasmic-import: TKT8XnZtrLZi/component
import Clubs2 from "../../Clubs2"; // plasmic-import: 3EueAFP_3sEI/component
import SearchComponent from "../../SearchComponent"; // plasmic-import: mmk_GiTXUtux/component
import AvatarPlayer from "../../AvatarPlayer"; // plasmic-import: 4QnaRcOLXj0D/component
import MessageCard from "../../MessageCard"; // plasmic-import: KNRpEkS9bXP0/component
import Select from "../../Select"; // plasmic-import: bCMc_ebYmgPo/component
import Footer from "../../Footer"; // plasmic-import: kIdovXGtWiEz/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: tDWy3GXn2mzd9e2xUaPdmu/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: Bqv9LwfAil9f/css

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select5.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select6.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    players: usePlasmicDataOp(() => {
      return {
        sourceId: "8cdHi4ivRUEkK6qbegQevF",
        opId: "5686467a-3f07-4485-a16e-2f82f62ffb56",
        userArgs: {},
        cacheKey: `plasmic.$.5686467a-3f07-4485-a16e-2f82f62ffb56.$.`,
        invalidatedKeys: null,
        roleId: "f8970d3a-c1ae-4ba8-80dd-90e548ee70d6"
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <Clubs2
            data-plasmic-name={"clubs2"}
            data-plasmic-override={overrides.clubs2}
            className={classNames("__wab_instance", sty.clubs2)}
          />

          <Stack__
            as={"div"}
            data-plasmic-name={"heroSection"}
            data-plasmic-override={overrides.heroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.heroSection)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__aMoxZ)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={
                "https://dlcdnwebimgs.asus.com/gain/3EF83AFB-7D9C-4D1A-918E-8910190606D1/fwebp"
              }
              width={"800px"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qIiUy
              )}
            >
              {
                "\u0418\u0433\u0440\u0430\u0439\u0442\u0435 \u0441 \u043d\u0430\u043c\u0438 \u0438 \u043f\u043e\u043b\u0443\u0447\u0430\u0439\u0442\u0435 \u043f\u043e\u0434\u0430\u0440\u043a\u0438!"
              }
            </div>
          </Stack__>
          <SearchComponent
            data-plasmic-name={"searchComponent"}
            data-plasmic-override={overrides.searchComponent}
            className={classNames("__wab_instance", sty.searchComponent)}
          />

          <div className={classNames(projectcss.all, sty.columns__hmshc)}>
            <div className={classNames(projectcss.all, sty.column__ubaBx)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__smc8L
                )}
              >
                {
                  "\u0421\u041e\u0411\u0420\u0410\u0422\u042a  \u041a\u041e\u041c\u0410\u041d\u0414\u0423"
                }
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ipYwg)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"playersTable"}
                  data-plasmic-override={overrides.playersTable}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.playersTable)}
                >
                  <div
                    data-plasmic-name={"goa"}
                    data-plasmic-override={overrides.goa}
                    className={classNames(projectcss.all, sty.goa)}
                  >
                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__eYqn
                      )}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"def"}
                    data-plasmic-override={overrides.def}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.def)}
                  >
                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__zHe2
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__gKg6U
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__gy4Be
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__fMyT
                      )}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"mid"}
                    data-plasmic-override={overrides.mid}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.mid)}
                  >
                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__scu4E
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__rwYkb
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__ytkgs
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__dwZcr
                      )}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"str"}
                    data-plasmic-override={overrides.str}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.str)}
                  >
                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__rJ1Bo
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer__dLfj0
                      )}
                    />

                    <AvatarPlayer
                      className={classNames(
                        "__wab_instance",
                        sty.avatarPlayer___0Fap9
                      )}
                    />
                  </Stack__>
                </Stack__>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qLnOw)}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__lzWbv
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  platform={"nextjs"}
                >
                  {
                    "\u041d\u0410\u0417\u0412 \u041a\u041e\u041c\u0410\u041d\u0414"
                  }
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___72HwL
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  platform={"nextjs"}
                >
                  {"\u041a\u0410\u041f\u0418\u0422\u0410\u041d"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__exs7U
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  platform={"nextjs"}
                >
                  {"\u0421\u041eX\u0420\u0410\u041d\u0418\u0422\u042a"}
                </PlasmicLink__>
              </Stack__>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column___7Ggbf)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ru5GL
                )}
              >
                {"\u041f\u0420\u0410\u0412\u0418\u041b\u0418!"}
              </div>
              <MessageCard
                className={classNames("__wab_instance", sty.messageCard__hDvns)}
                heading={"Qoida 1"}
                textInfo={
                  "Har bir o'yinda bir komandadan faqat 2 ta o'yinchi sotib olsa bo'ladi! Qolgan o'yinchilar uchun to'lov amalga oshiriladi"
                }
              />

              <MessageCard
                className={classNames(
                  "__wab_instance",
                  sty.messageCard___4RSaU
                )}
                heading={"Qoida 2"}
                textInfo={
                  "Sotib olinga o'yinchilar 100 dan oshib ketmasligi kerak"
                }
              />

              <MessageCard
                className={classNames(
                  "__wab_instance",
                  sty.messageCard___2ONt1
                )}
                heading={"Qoida 3"}
                textInfo={
                  "Har turda 2 ta dan ortiq transferlar qilib bo'lmaydi!"
                }
              />

              <MessageCard
                className={classNames("__wab_instance", sty.messageCard__apEks)}
                heading={"Qoida 4"}
                textInfo={"Savollar bo'yicha Moderatorga murojaat qiling!"}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column__ljt9J)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qp8Lp
                )}
              >
                {"\u041f\u0420\u0410\u0412\u0418\u041b\u0418!"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nZk)}
              >
                <Select
                  data-plasmic-name={"select"}
                  data-plasmic-override={overrides.select}
                  className={classNames("__wab_instance", sty.select)}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["select", "value"])(
                      eventArgs[0]
                    );
                  }}
                  options={[
                    { value: "option1", label: "Option 1" },
                    { value: "option2", label: "Option 2" }
                  ]}
                  placeholder={
                    "-\u0412\u0441\u0435 \u043a\u043b\u0443\u0431\u044b"
                  }
                  value={generateStateValueProp($state, ["select", "value"])}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__olZs)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hP66M
                  )}
                >
                  {"\u0426\u0435\u043d\u0430 \u043e\u0442"}
                </div>
                <Select
                  data-plasmic-name={"select2"}
                  data-plasmic-override={overrides.select2}
                  className={classNames("__wab_instance", sty.select2)}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["select2", "value"])(
                      eventArgs[0]
                    );
                  }}
                  options={[
                    { value: "option1", label: "Option 1" },
                    { value: "option2", label: "Option 2" }
                  ]}
                  placeholder={"40"}
                  value={generateStateValueProp($state, ["select2", "value"])}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___4FfY4)}
              >
                <Select
                  data-plasmic-name={"select5"}
                  data-plasmic-override={overrides.select5}
                  className={classNames("__wab_instance", sty.select5)}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["select5", "value"])(
                      eventArgs[0]
                    );
                  }}
                  options={[
                    { value: "option1", label: "Option 1" },
                    { value: "option2", label: "Option 2" }
                  ]}
                  placeholder={
                    "-\u0412\u0441\u0435  \u0438\u0433\u0440\u043e\u043a\u0438"
                  }
                  value={generateStateValueProp($state, ["select5", "value"])}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__bdilj)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ahhtc
                  )}
                >
                  {"\u0414\u043e"}
                </div>
                <Select
                  data-plasmic-name={"select6"}
                  data-plasmic-override={overrides.select6}
                  className={classNames("__wab_instance", sty.select6)}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["select6", "value"])(
                      eventArgs[0]
                    );
                  }}
                  options={[
                    { value: "option1", label: "Option 1" },
                    { value: "option2", label: "Option 2" }
                  ]}
                  placeholder={"12,0"}
                  value={generateStateValueProp($state, ["select6", "value"])}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tfmIo)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Rqje
                  )}
                >
                  {"\u0418\u0433\u0440\u043e\u043a"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nXnUk
                  )}
                >
                  {"\u041e\u0447\u043a\u0438"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___04Pyj
                  )}
                >
                  {"\u0426\u0435\u043d\u0430"}
                </div>
              </Stack__>
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return $queries.players.data;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__f0IVw)}
                    key={currentIndex}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__y5KrK)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={"https://cdn-icons-png.flaticon.com/512/1/1176.png"}
                      width={"14px"}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hz3Ct)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://cdn-icons-png.freepik.com/512/5974/5974633.png"
                      }
                      width={"14px"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__me2YB
                      )}
                    >
                      {"\u041c\u0435\u0441\u0441\u0438"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__winha
                      )}
                    >
                      {"11"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ezFd
                      )}
                    >
                      {"10,5"}
                    </div>
                  </div>
                );
              })}
              <div className={classNames(projectcss.all, sty.freeBox___7GljZ)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jNvEx
                  )}
                >
                  {
                    "\u041f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0439"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l2Bv
                  )}
                >
                  {"|"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bIGh
                  )}
                >
                  {"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0439"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.columns__mFen7)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column___2E1RK)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eOCd
                )}
              >
                {"\u0418\u0433\u0440\u044b"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___1F1Kc)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tfyri)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t3.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y0Kx3
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lJtcL
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cwhfo
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mTwCg)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t8.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___7MuNc)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lyYBn)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t14.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__klcN9
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dZokZ
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ngAl
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jpV5K)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t49.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__nswPv)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fNjj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t21.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nVwBu
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hE7ZA
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iiP1
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xz9B8)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t6.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lSveU)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___6Hq8Q)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t102.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ych0Y
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gaFu
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cEhwp
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eIrOq)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t8.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__x7Yjm)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___4SNLz)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t3.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cvKng
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5YDjs
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jle3B
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__odgSd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t31.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__b3Ks)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___4Box9)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t39.png"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rVpEu
                  )}
                >
                  {"Arsenal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8YXf
                  )}
                >
                  {"21:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s8Mpk
                  )}
                >
                  {"Chelsea"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uIaHw)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t8.png"
                  }
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.column__w2Ixm)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__jcG8)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://www.creatopy.com/blog/wp-content/uploads/2016/05/Ebay-420x600.png"
                }
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__d53Iu)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zjZe1
                )}
              >
                {
                  "\u0421\u0432\u044f\u0437\u0430\u0442\u044c\u0441\u044f \u0441 \u043d\u0430\u043c\u0438"
                }
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__br8Ag)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__djMtZ)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__zSyD4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Telegram_2019_Logo.svg/2048px-Telegram_2019_Logo.svg.png"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cTmnU)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhqhCE1ZItBk2eXdpda7hUVibZjDbg_iVhUzQ1_xvmjQ&s"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5Ra7A)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Odnoklassniki.svg/1200px-Odnoklassniki.svg.png"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__v6Ff)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/512px-Logo_of_Twitter.svg.png"
                  }
                />
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___6H1Lm)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://lh5.googleusercontent.com/s33DzDKEMEHPerhhGM8VZxT2NQbWzvjqQDfN0m_cgVSE4GS1JgeF9illZxM4AleZLqpjpGU9oVPkL1CYniGp53lQSbDLDkrf0n3gid1ZAGO1ad6UDML3Lvfk5TBDB9N0sD3adio_"
                }
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.columns__dioX)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column__dY1Z8)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Hjdd
                )}
              >
                {"\u041d\u043e\u0432\u043e\u0441\u0442\u0438"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bwAt)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gNxV8
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dyz7H
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__cKGo6)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dbYba
                  )}
                >
                  {"16:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5FzwA
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__itf9G)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Lm0B
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jcm90
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__w5XLt)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bb231
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e36SH
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__asMut)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wLpZ
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y1Opr
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__z30Rr)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cbWfn
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dxqg7
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__n615V)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w84ZK
                  )}
                >
                  {"14:00"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o5E9
                  )}
                >
                  {
                    "\u0418\u0433\u0440\u043e\u043a \u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0443\u0437\u043d\u0430\u043b \u043e\u0431 \u044d\u0442\u043e\u043c"
                  }
                </div>
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.column__ifeDh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wkeHe
                )}
              >
                {"\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435"}
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xtpA5)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://img.chelseafc.com/image/upload/f_auto,ar_16:9,w_500,c_fill,g_auto,q_90/editorial/news/2024/05/21/Richard_Olise_Chelsea_defender.jpg"
                }
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eHuVg
                )}
              >
                {
                  "\u00ab\u0427\u0435\u043b\u0441\u0438\u00bb \u0445\u043e\u0447\u0435\u0442 \u043f\u0440\u0438\u043e\u0431\u0440\u0435\u0441\u0442\u0438 \u0438\u0433\u0440\u043e\u043a\u0430 \u0438\u0437 \u041b\u0430 \u041b\u0438\u0433\u0438."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__ycZ7Y)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bS99H
                )}
              >
                {"\u0442\u0430\u0431\u043b\u0438\u0446\u044c "}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jGqfr)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hyYfi
                  )}
                >
                  {"\u0418\u0441\u043f\u0430\u043d\u0438\u044f"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__nKbvV)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://flagdownload.com/wp-content/uploads/Flag_of_Spain_Flat_Round.png"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__vcpuP)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q3Eyj
                  )}
                >
                  {"O\u0431"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Z5WV
                  )}
                >
                  {"T/S"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uOOq0
                  )}
                >
                  {"O"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bqHCq)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x3Ys4
                  )}
                >
                  {"\u041c\u0430\u0434\u0440\u0438\u0434"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__foOtP)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://seeklogo.com/images/R/real-madrid-club-crest-new-logo-03D0B23BC4-seeklogo.com.png"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__jJFrc)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dMLfx
                  )}
                >
                  {"12"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d7Re
                  )}
                >
                  {"9"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6S3JN
                  )}
                >
                  {"15"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jnbNd)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rQx7R
                  )}
                >
                  {"\u041c\u0430\u0434\u0440\u0438\u0434"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__b61If)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://1000logos.net/wp-content/uploads/2018/05/Atletico-Madrid-Logo.png"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___6GjaG)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vxv67
                  )}
                >
                  {"12"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__drsju
                  )}
                >
                  {"9"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pcjSo
                  )}
                >
                  {"15"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vH7Xq)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fkE4N
                  )}
                >
                  {"\u041c\u0430\u0434\u0440\u0438\u0434"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__icD35)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://upload.wikimedia.org/wikipedia/sco/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__d8TKw)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hl0PT
                  )}
                >
                  {"12"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zKbfG
                  )}
                >
                  {"9"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jaXhm
                  )}
                >
                  {"15"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___1Rl5P)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fxlkE
                  )}
                >
                  {"\u041c\u0430\u0434\u0440\u0438\u0434"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uWuZb)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://logowik.com/content/uploads/images/526_liverpoolfc.jpg"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__x3MJn)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Rfy4
                  )}
                >
                  {"12"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i37HZ
                  )}
                >
                  {"9"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fZkA
                  )}
                >
                  {"15"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6Bcxj)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b5ANs
                  )}
                >
                  {"\u041c\u0430\u0434\u0440\u0438\u0434"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rfGan)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={"14px"}
                  loading={"lazy"}
                  src={
                    "https://resources.premierleague.com/premierleague/badges/50/t1.png"
                  }
                  width={"14px"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___4UmHm)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qOdCq
                  )}
                >
                  {"12"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___77NFm
                  )}
                >
                  {"9"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lYtwv
                  )}
                >
                  {"15"}
                </div>
              </Stack__>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "clubs2",
    "heroSection",
    "searchComponent",
    "playersTable",
    "goa",
    "def",
    "mid",
    "str",
    "select",
    "select2",
    "select5",
    "select6",
    "footer"
  ],

  navbar: ["navbar"],
  clubs2: ["clubs2"],
  heroSection: ["heroSection"],
  searchComponent: ["searchComponent"],
  playersTable: ["playersTable", "goa", "def", "mid", "str"],
  goa: ["goa"],
  def: ["def"],
  mid: ["mid"],
  str: ["str"],
  select: ["select"],
  select2: ["select2"],
  select5: ["select5"],
  select6: ["select6"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard(WrappedComponent) {
  const PageGuard = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"tDWy3GXn2mzd9e2xUaPdmu"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    clubs2: makeNodeComponent("clubs2"),
    heroSection: makeNodeComponent("heroSection"),
    searchComponent: makeNodeComponent("searchComponent"),
    playersTable: makeNodeComponent("playersTable"),
    goa: makeNodeComponent("goa"),
    def: makeNodeComponent("def"),
    mid: makeNodeComponent("mid"),
    str: makeNodeComponent("str"),
    select: makeNodeComponent("select"),
    select2: makeNodeComponent("select2"),
    select5: makeNodeComponent("select5"),
    select6: makeNodeComponent("select6"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
